### ISSUE TITLE
Publish library to Central Repository

### ISSUE THREAD

**Issue by chrismattmann** [shivensaiwal/PersonaExtraction#3]
See https://github.com/manalishah/NLTKRest/issues/7

**Comment by chrismattmann** [comment]
ping @shivensaiwal @smadha can you help too you too @manalishah please help shiven

**Comment by shivensaiwal** [comment]
@chrismattmann published the jar to the central repository. Link is shared via email.

**Comment by smadha** [comment]
@shivensaiwal This commit might interest you too
https://github.com/smadha/NLTKRest/commit/26a30a792a535a1b7f28a5fb34ea2bb1e69cc8ec
https://gist.github.com/aslakknutsen/9648594
